name: Docker Build and Test Release for GHCR tag

on:
  push:
    branches: 
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: release
    - name: Set Container Version
      run: echo "CONTAINER_VERSION=`awk '/VERSION /{print $3}' Makefile`" >> $GITHUB_ENV
      id: version-generator
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: dotnet test tests --verbosity normal
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: Cingulara
        password: ${{ secrets.OPENRMFPRO_PACKAGE_DOCKER }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: DaleBinghamSoteriaSoft
        password: ${{ secrets.OPENRMFPRO_PACKAGE_DOCKER }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/soteriasoftwarellc/openrmfpro-msg-artifact:${{ env.CONTAINER_VERSION }}
    - name: Container image scan
      uses: anchore/scan-action@v3
      with:
        image: ghcr.io/soteriasoftwarellc/openrmfpro-msg-artifact:${{ env.CONTAINER_VERSION }}
        registry-username: DaleBinghamSoteriaSoft
        registry-password: ${{ secrets.OPENRMFPRO_PACKAGE_DOCKER }}
        fail-build: false
        output-format: table